### ISSUE TITLE
azure: add support for uploading files >4MB

### ISSUE THREAD

**Issue by piotrrojek** [graymeta/stow#72]
Currently Azure implementation supports only `put`ting/uploading files smaller than 4MB. We should be able to upload files of arbitrary size.

**Comment by pieterclaerhout** [comment]
In the case of Block Blobs, you need first to create a block block. Then add different block, each maximum 4MB. Each block should have a unique ID so that you can use them after uploading with PutBlockList to combine them into a single file.

The Azure Storage Python SDK for example has some helpers to do this:

https://github.com/Azure/azure-storage-python/blob/master/azure/storage/blob/_upload_chunking.py

Apparently, you could also use PutAppendBlob and AppendBlog to do the same (see https://github.com/Azure/azure-sdk-for-go/issues/129#issuecomment-229263839)

**Comment by pieterclaerhout** [comment]
The following repo might give you some clues on how to do this:

https://github.com/schreibe72/abc

**Comment by jasonhancock** [comment]
fixed in https://github.com/graymeta/stow/pull/162
